name: Bug Report
description: Report a bug or issue with TherapyLink
title: "[Bug] "
labels: ["bug", "beta-feedback"]
assignees: []
projects:
  - "redducklabs/TherapyLink"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! This form is automatically filled when submitting feedback through the TherapyLink application, but you can also use it directly.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: false

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Low (Minor inconvenience)
        - Medium (Impacts workflow)
        - High (Prevents work)
        - Critical (System down)
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context about the problem
      placeholder: |
        - Browser: [e.g. Chrome 120.0]
        - Operating System: [e.g. Windows 11]
        - User Role: [e.g. Service Manager]
        - URL: [e.g. https://dev.therapy-link.org/students]
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here or paste them
    validations:
      required: false